[package]
name = "opencall-mls"
version = "0.1.0"
edition = "2021"
authors = ["OpenCall Contributors"]
license = "MIT"
description = "MLS Protocol WebAssembly bindings for OpenCall"

[lib]
crate-type = ["cdylib"]

[dependencies]
openmls = { version = "0.6", default-features = false, features = ["libcrux-provider"] }
openmls_basic_credential = "0.3"
openmls_rust_crypto = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
web-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }
thiserror = "1.0"
hex = "0.4"
async-trait = "0.1"
base64 = "0.22"
console_error_panic_hook = "0.1"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "Window",
  "Crypto",
  "SubtleCrypto"
]

[profile.release]
lto = "fat"
opt-level = "z"
codegen-units = 1
strip = true
panic = "abort"

[target.'cfg(target_feature = "atomics")'.dependencies]
wasm-bindgen-rayon = "1.2"

[features]
default = []
simd = []
parallel = ["wasm-bindgen-rayon"]

[dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.wasm-pack]
"wasm-opt" = ["-Oz", "--enable-simd", "--enable-threads", "--enable-bulk-memory", "--enable-mutable-globals"]