[package]
name = "dmp-mls"
version = "0.1.0"
edition = "2021"
authors = ["DMP Contributors"]
license = "MIT"
description = "MLS Protocol WebAssembly bindings for the decentralized meeting platform"

[lib]
crate-type = ["cdylib"]

[dependencies]
mls-rs = "0.40"
mls-rs-provider-rustcrypto = "0.40"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
web-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }
thiserror = "1.0"
hex = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "Window",
  "Crypto",
  "SubtleCrypto"
]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
strip = true

[package.metadata.wasm-pack]
"wasm-opt" = ["-Oz"]